Added a README file
Uwampojejecharly/mavenTraining pull request #5
Opened 2024-04-24 16:27 UTC by Uwampojejecharly

2024-04-29 04:08 UTC, fayabobo requested changes
I think the text you put in the description says more than this one. So just use the same text.

2024-04-29 10:38 UTC, Uwampojejecharly commented
Done

2024-04-30 06:55 UTC, fayabobo requested changes
Again, as I wrote in my last comment, just use the description of the project in the read me. By description I mean the one you already added in the description of the project.

2024-05-01 23:41 UTC, fayabobo approved these changes

2024-05-01 23:41 UTC, merged